project_id = "vzhympxsxzerubkribos"

[functions.create-lifetime-checkout]
verify_jwt = false

[functions.create-monthly-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.update-pricing]
verify_jwt = false

[functions.create-coupon]
verify_jwt = false

[functions.send-profile-welcome]
verify_jwt = false

[functions.send-signup-welcome]
verify_jwt = false

[functions.send-purchase-confirmation]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false